//get ArticleData
export const FETCH_ARTICLE_DATA = "FETCH_ARTICLE_DATA";
export const FETCH_ARTICLE_DATA_SUCCESS = "FETCH_ARTICLE_DATA_SUCCESS";
export const FETCH_ARTICLE_DATA_FAILED = "FETCH_ARTICLE_DATA_FAILED";

export const FETCH_ALL_TEACHERS = "FETCH_ALL_TEACHERS";
export const FETCH_ALL_TEACHERS_SUCCESS = "FETCH_ALL_TEACHERS_SUCCESS";
export const FETCH_ALL_TEACHERS_FAILED = "FETCH_ALL_TEACHERS_FAILED";
//Register user
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILED = "REGISTER_USER_FAILED";
//login User
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";
//get user
export const GET_USER = "GET_USER";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_DATA_FAILED = "GET_USER_DATA_FAILED";
//Delete User Account
export const DELETE_USER_ACCOUNT = "DELETE_USER_ACCOUNT";
export const DELETE_USER_ACCOUNT_SUCCESS = "DELETE_USER_ACCOUNT";
export const DELETE_USER_ACCOUNT_FAILED = "DELETE_USER_ACCOUNT";
//Adding article Data
export const Add_ARTICLE_DATA = "Add_ARTICLE_DATA";
export const Add_ARTICLE_DATA_SUCCESS = "Add_ARTICLE_DATA_SUCCESS";
export const Add_ARTICLE_DATA_FAILED = "Add_ARTICLE_DATA_FAILED";
//Delete Article Data
export const DELETE_ARTICLE_DATA = "DELETE_ARTICLE_DATA";
export const DELETE_ARTICLE_DATA_SUCCESS = "DELETE_ARTICLE_DATA_SUCCESS";
export const DELETE_ARTICLE_DATA_FAILED = "DELETE_ARTICLE_DATA_FAILED";
//update courseDAta
export const UPDATE_ARTICLE_DATA = "UPDATE_ARTICLE_DATA";
export const UPDATE_ARTICLE_DATA_SUCCESS = "UPDATE_ARTICLE_DATA_SUCCESS";
export const UPDATE_ARTICLE_DATA_FAILED = "UPDATE_ARTICLE_DATA_FAILED";

// Changing language type
export const CHANGE_TO_CHAKMALANGUAGE = "CHANGE_TO_CHAKMALANGUAGE";
//GETARTICLE Card
export const GET_ARTICLECARD = "GET_ARTICLECARD";
export const GET_ARTICLECARD_SUCCESS = "GET_ARTICLECARD_SUCCESS";
export const GET_ARTICLECARD_FAILED = "GET_ARTICLECARD_SUCCESS";

//GETARTICLEBYID
export const GET_ARTICLEBY_ID = "GET_ARTICLEBY_ID";
export const GET_ARTICLEBY_ID_SUCCESS = "GET_ARTICLEBY_ID_SUCCESS";
export const GET_ARTICLEBY_ID_FAILED = "GET_ARTICLEBY_ID_FAILED";

//Gets all review
export const GET_REVIEWS = "GET_REVIEWS";
export const GET_REVIEWS_SUCCESS = "GET_REVIEWS_SUCCESS";
export const GET_REVIEWS_FAILED = "GET_REVIEWS_FAILED";

//add reviw
export const ADD_REVIEW = "ADD_REVIEW";
export const ADD_REVIEW_SUCCESS = "ADD_REVIEW_SUCCESS";
export const ADD_REVIEW_FAILED = "ADD_REVIEW_FAILED";

//rmovoe remove by admin
export const REMOVE_REVIEW = "REMOVE_REVIEW";
export const REMOVE_REVIEW_SUCCESS = "REMOVE_REVIEW_SUCCESS";
export const REMOVE_REVIEW_FAILED = "REMOVE_REVIEW_FAILED";

//update review
export const UPDATE_REVIEW = "UPDATE_REVIEW";
export const UPDATE_REVIEW_SUCCESS = "UPDATE_REVIEW_SUCCESS";
export const UPDATE_REVIEW_FAILED = "UPDATE_REVIEW_FAILED";
//find by email

export const GET_REVIEW_BYMAIL = "GET_REVIEW_BYMAIL";
export const GET_REVIEW_BYMAIL_SUCCESS = "GET_REVIEW_BYMAIL_SUCCESS";
export const GET_REVIEW_BYMAIL_FAILED = "GET_REVIEW_BYMAIL_FAILED";

//get all tour guides
export const GET_ALL_TOUR_GUIDES = "GET_ALL_TOUR_GUIDES";
export const GET_ALL_TOUR_GUIDES_SUCCESS = "GET_ALL_TOUR_GUIDES_SUCCESS";
export const GET_ALL_TOUR_GUIDES_FAILED = "GET_ALL_TOUR_GUIDES_FAILED";

//get tour guide
export const GET_TOUR_GUIDE = "GET_TOUR_GUIDES";
export const GET_TOUR_GUIDE_SUCCESS = "GET_TOUR_GUIDES_SUCCESS";
export const GET_TOUR_GUIDE_FAILED = "GET_TOUR_GUIDES_FAILED";

//update tour guide
export const UPDATE_TOUR_GUIDE = "UPDATE_TOUR_GUIDE";
export const UPDATE_TOUR_GUIDE_SUCCESS = "UPDATE_TOUR_GUIDE_SUCCESS";
export const UPDATE_TOUR_GUIDE_FAILED = "UPDATE_TOUR_GUIDE_FAILED";

//remove toru guides
export const REMOVE_TOUR_GUIDE = "REMOVE_TOUR_GUIDE";
export const REMOVE_TOUR_GUIDE_SUCCESS = "REMOVE_TOUR_GUIDE_SUCCESS";
export const REMOVE_TOUR_GUIDE_FAILED = "REMOVE_TOUR_GUIDE_FAILED";

//addTour guide
export const ADD_TOUR_GUIDE = "ADD_TOUR_GUIDE";
export const ADD_TOUR_GUIDE_SUCCESS = "ADD_TOUR_GUIDE_SUCCESS";
export const ADD_TOUR_GUIDE_FAILED = "ADD_TOUR_GUIDE_FAILED";
