//get ArticleData
export const FETCH_ARTICLE_DATA = "FETCH_ARTICLE_DATA";
export const FETCH_ARTICLE_DATA_SUCCESS = "FETCH_ARTICLE_DATA_SUCCESS";
export const FETCH_ARTICLE_DATA_FAILED = "FETCH_ARTICLE_DATA_FAILED";

export const FETCH_ALL_TEACHERS = "FETCH_ALL_TEACHERS";
export const FETCH_ALL_TEACHERS_SUCCESS = "FETCH_ALL_TEACHERS_SUCCESS";
export const FETCH_ALL_TEACHERS_FAILED = "FETCH_ALL_TEACHERS_FAILED";
//Register user
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILED = "REGISTER_USER_FAILED";
//login User
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";
//get user
export const GET_USER = "GET_USER";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_DATA_FAILED = "GET_USER_DATA_FAILED";
//Delete User Account
export const DELETE_USER_ACCOUNT = "DELETE_USER_ACCOUNT";
export const DELETE_USER_ACCOUNT_SUCCESS = "DELETE_USER_ACCOUNT";
export const DELETE_USER_ACCOUNT_FAILED = "DELETE_USER_ACCOUNT";
//Adding article Data
export const Add_ARTICLE_DATA = "Add_ARTICLE_DATA";
export const Add_ARTICLE_DATA_SUCCESS = "Add_ARTICLE_DATA_SUCCESS";
export const Add_ARTICLE_DATA_FAILED = "Add_ARTICLE_DATA_FAILED";
//Delete Article Data
export const DELETE_ARTICLE_DATA = "DELETE_ARTICLE_DATA";
export const DELETE_ARTICLE_DATA_SUCCESS = "DELETE_ARTICLE_DATA_SUCCESS";
export const DELETE_ARTICLE_DATA_FAILED = "DELETE_ARTICLE_DATA_FAILED";
//update courseDAta
export const UPDATE_ARTICLE_DATA = "UPDATE_ARTICLE_DATA";
export const UPDATE_ARTICLE_DATA_SUCCESS = "UPDATE_ARTICLE_DATA_SUCCESS";
export const UPDATE_ARTICLE_DATA_FAILED = "UPDATE_ARTICLE_DATA_FAILED";

export const FIND_DATA_BYID = "FIND_DATA_BYID";
export const FIND_DATA_BYID_SUCCESS = "FIND_DATA_BYID_SUCCESS";
export const FIND_DATA_BYID_FAILED = "FIND_DATA_BYID_FAILED";

// Changing language type
export const CHANGE_TO_CHAKMALANGUAGE = "CHANGE_TO_CHAKMALANGUAGE";
